[package]
name = "slotted-pig-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
csv = "1"
glob = "0.3"
serde_yaml = "0.9"
slotted-pig-lib = { path = "../slotted-pig-lib" }
sloggers = "2"
slog = "2"
