[workspace]
resolver = "2"
members = ["slotted-pig-cli", "slotted-pig-ui", "slotted-pig-lib"]

# # TODO: put this behind the wasm target
[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true
incremental = false
