name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: sudo apt-get install libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev
      - name: Build
        run: cargo build --verbose
      - name: Run clippy
        run: cargo clippy --verbose
      - name: Run tests
        run: cargo test --verbose

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Dioxus Deploy"
        uses: DioxusLabs/deploy-action@v5
        with:
          buildMode: "release"
          toolchain: "stable"
          outDirectory: "slotted-pig-ui/dist"
          rootPath: "slotted-pig-ui"
